baseURL = ''
languageCode = 'en-us'
title = 'Andre Afonso'
theme = 'hugo-theme-sam'
pygmentsStyle = "monokai"  # https://help.farbox.com/pygments.html
pygmentsCodefences = true
# googleAnalytics = ""  # Tracking code, eg. "UA-111111111-1"

[security]
  enableInlineShortcodes = true

[params]
    homepage = "home"
    footerText = "What defines me: \"Let's do it!\""

[[params.mainMenu]]
    link = "/about"
    text = "Who's Andre?"

[[params.mainMenu]]
    link = "/jobs"
    text = "@ Work"

[[params.mainMenu]]
    link = "/music"
    text = "@ Music"

[[params.mainMenu]]
    link = "/random"
    text = "@ Thinking"