baseURL = 'https://www.andreafonso.pt'
languageCode = 'en-us'
title = 'Andre Afonso'
theme = 'archie'
pygmentsStyle = "monokai"  # https://help.farbox.com/pygments.html
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
# googleAnalytics = ""  # Tracking code, eg. "UA-111111111-1"

[params]
    mode="dark" # color-mode → light,dark,toggle or auto
    useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
    subtitle = "My perspective of the world we live in"
    mathjax = true # enable MathJax support
    katex = true # enable KaTeX support
    #homepage = "home"
    #footerText = "Cyber enthusiasm guaranteed"

#[[params.mainMenu]]
#    link = "/posts"
#    text = "Some things I write"
#
#[[params.mainMenu]]
#    link = "/about"
#    text = "Who's Andre?"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "My perspective"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3
